# AppCenter CLI
#
# Triggers are configured in the UI

jobs:
- job:

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'Medium'
      failOnAlert: true

  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - script: |
      npm test
    displayName: 'npm test'

  - script: |
      npm pack
    displayName: 'Package for npm release'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: '*.tgz' 
      targetFolder: $(Build.ArtifactStagingDirectory)/npm
    displayName: 'Copy npm package'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: 'package.json' 
      targetFolder: $(Build.ArtifactStagingDirectory)/npm
    displayName: 'Copy package.json'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: 'package-lock.json' 
      targetFolder: $(Build.ArtifactStagingDirectory)/npm
    displayName: 'Copy package-lock.json'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/npm'
      artifactName: npm
    displayName: 'Publish npm artifact'
