# AppCenter CLI
#
# Triggers are configured in the UI

jobs:
- job:

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npm run build
    displayName: 'npm install and build'

  - task: ComponentGovernanceComponentDetection@0
    displayName: Component Governance (PR)
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'
      failOnAlert: true
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))

  - task: ComponentGovernanceComponentDetection@0
    displayName: Component Governance (CI)
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'
      failOnAlert: false
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  - script: |
      npm test
    displayName: 'npm test'

  - publish: $(System.DefaultWorkingDirectory)
    artifact: Workspace